spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: zyh123456

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启在mybatis处理过程中打印出对应的sql语句功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

   #开启数据库字段自动转换为驼峰命名
#    map-underscore-to-camel-case: true

#配置分页插件
#照着写就行，别问为什么
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


server:
  port: 8888
  
# spring 读取配置文件中的数据 。 @value("${user.address.max-count}")
user:
  address:
    max-count: 20

#站在宏观的角度看问题

#日志文件
logging:
  level:
    root: info
  file:
    path: E:\日志\sale
